models/Category.js
models/Manager.js
models/Order.js
models/OrderLogs.js
models/Post.js
models/ProductImage.js
models/Seller.js

- 판매자, 판매글, 구매, 중개내역, 관리자, 카테고리, 판매 이미지 모델 생성
테이블 생성 완료 확인했습니다~

Feat: model 생성

---

controller/cart/Ccart.js
routes/cart/cart.js

PR : 장바구니 내역 조회, 생성, 삭제

---

controller/cart/Ccart.js

PR : 장바구니 내역 조회 주석 추가

---

controller/user/Cseller.js
controller/user/Cuser.js
routes/user/user.js

Feat: Cuser

---

controller/cart/Ccart.js

PR: 장바구니 내역 컬럼 변경

---

controller/mypage/Cmypage.js
routes/mypage/mypage.js

- mypage controller, routers 작성

Feat: mypage controller, routers 작성

---

controller/complaint/Ccomplaint.js
routes/complaint/complaint.js

PR: 신고 등록 api

---

controller/cart/Ccart.js
controller/mypage/Cmypage.js
controller/seller/Cseller.js
controller/user/Cuser.js
routes/user/user.js

- Cuser, Cmypage, Ccart, Cseller session 설정
- user routes 동적 경로 관련 문제 해결

Feat: session 설정

---

controller/user/Cuser.js

회원가입 시 잔고는 백에서 랜덤 생성, 배송지명은 '집'으로 insert, 배송지 기본여부는 true로 insert

PR: 회원가입 관련 코드 변경

---

controller/index.js
routes/index.js

PR: 메인 페이지 이동 api 추가

---

controller/comment/Ccomment.js
routes/comment/comment.js

PR: 댓글 관련 api

---

controller/cart/Ccart.js

PR: 장바구니 등록 로직 추가

---

controller/user/Cuser.js
middlewares/multer.js
routes/user/user.js

PR: multer 추가

---

controller/post/Cpost.js
routes/post/post.js

PR: 판매글 수정 페이지 이동 추가

---

controller/post/Cpost.js

PR: 판매글 상세 페이지 이동 구현

---

controller/mypage/Cmypage.js

PR: 송장 번호 입력 수정, 판매 내역 페이지 이동 수정

PR: 송장 번호 입력 수정, 판매 내역 페이지 이동 수정

---

controller/admin/Cadmin.js
routes/admin/admin.js

PR: 관리자 페이지 추가

---

controller/post/Cpost.js
middlewares/multer.js
routes/post/post.js
routes/seller/seller.js

상품 판매글 등록시 복수의 이미지를 전달하는 경우 -> DB 에 이미지의 url 을 전달할 때 , 앞부분이 등록되지 않는 현상이 발생?
명시적으로 기입해주는 경우에도 누락되어 기록되고있음

PR : 상품 판매글 등록시 이미지 를 aws 에 전달

---

controller/post/Cpost.js
routes/post/post.js

PR: 판매글 상세에 찜여부 포함

---

controller/post/Cpost.js
controller/user/Cuser.js
routes/user/user.js

Feat : 유저 정보 수정시 이미지 추가 가능

---

controller/admin/Cadmin.js
routes/admin/admin.js

PR: 관리자 api 추가(구매내역 조회 제외 테스트까지)

PR: 관리자 api 추가(구매내역 조회 제외 테스트까지)

---

controller/user/Cuser.js

PR: 로그인 로직 변경

---

controller/user/Cuser.js

PR: 로그인 로직 변경2

---

controller/admin/Cadmin.js
controller/mypage/Cmypage.js
routes/mypage/mypage.js

PR: 구매 확정 로직 추가, 관리자페이지 판매자조회 변경

PR: 구매 확정 로직 추가, 관리자페이지 판매자조회 변경

---

controller/admin/Cadmin.js
controller/index.js
routes/cart/cart.js

PR: 장바구니 내역 라우터 변경

---

controller/admin/Cadmin.js

PR: 블랙리스트 추가 구현

---

controller/index.js
controller/mypage/Cmypage.js

PR: 구매 내역 로직 변경, 메인 페이지 쿼리 변경

---

controller/address/Caddress.js
routes/post/post.js
routes/seller/seller.js
routes/user/user.js

PR: frontDev -> dev

---

controller/mypage/Cmypage.js

PR: 찜 목록 페이지, 판매글 목록 페이지 쿼리 변경

PR: 찜 목록 페이지, 판매글 목록 페이지 쿼리 변경

---

controller/admin/Cadmin.js

PR: 거래내역 조회 정렬 변경
